_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
        visualize:
            prediction distribution:
                panel_config:
                    fieldSettings:
                        value: Predictions [log(Kd)]
                    panelDefId: wandb/histogram/v0
                    stringSettings:
                        title: None
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: prediction distribution_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            test_affinity_table:
                panel_config:
                    fieldSettings:
                        x: True Binding Affinity
                        "y": Predicted Binding Affinity
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: ""
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: test_affinity_table_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            val_affinity_table:
                panel_config:
                    fieldSettings:
                        x: True Binding Affinity
                        "y": Predicted Binding Affinity
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: ""
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: val_affinity_table_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
best_params:
    value:
        batch_size: 128
        learning_rate: 0.01
        model_dense_neurons: 32
        model_embedding_size: 128
        model_layers: 3
        model_top_k_every_n: 1
        model_top_k_ratio: 0.5
        scheduler_gamma: 1
        sgd_momentum: 0.5
        weight_decay: 0.001
dataset:
    value:
        edge_inclusion_radius: 10
        max_logKd: 10.800759
        name: KLF1_K_d
        path: ../data/
        regenerate: false
        split_ratio:
            test: 0.1
            train: 0.8
            validation: 0.1
hyperparameters:
    value:
        batch_size:
            - 32
            - 128
            - 64
        learning_rate:
            - 0.1
            - 0.05
            - 0.01
            - 0.001
        model_dense_neurons:
            - 16
            - 128
            - 64
            - 256
            - 32
        model_embedding_size:
            - 8
            - 16
            - 32
            - 64
            - 128
        model_layers:
            - 3
        model_top_k_every_n:
            - 1
        model_top_k_ratio:
            - 0.2
            - 0.5
            - 0.8
            - 0.9
        scheduler_gamma:
            - 0.995
            - 0.9
            - 0.8
            - 0.5
            - 1
        sgd_momentum:
            - 0.9
            - 0.8
            - 0.5
        weight_decay:
            - 0.0001
            - 1e-05
            - 0.001
logging:
    value:
        log_interval: 10
        save_interval: 10
        save_model: true
trainer:
    value:
        early_stopping_patience: 100
        epochs: 100
tuner:
    value:
        initial_random: 1
        num_iteration: 10
        optimizer: Bayesian
utility:
    value:
        debug: false
        device: cuda
        num_workers: 4
        pin_memory: true
        seed: 42
        verbose:
            data: false
            hyperparameters: true
wandb:
    value:
        entity: mwfjord
        name: GNN Training
        project: structural_binding_affinity_predictions_using_gnn
        use_wandb: true
