_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
dataset:
    value:
        edge_inclusion_radius: 10
        max_Kd: 49058.026339486
        name: KLF1_K_d
        path: ../data/
        regenerate: false
        split_ratio:
            test: 0.1
            train: 0.8
            validation: 0.1
logging:
    value:
        log_interval: 10
        save_interval: 10
        save_model: true
model:
    value:
        activation: leakyrelu
        hidden_units: 512
        layers: 3
        type: GNN
training:
    value:
        T_0: 10
        T_mult: 2
        batch_size: 16
        early_stop_patience: 500
        ema_decay: 0.99
        epochs: 3000
        eta_min: 1e-06
        learning_rate: 0.001
        optimizer: adam
        seed: 42
        warmup_epochs: 5
utility:
    value:
        debug: false
        device: cuda
        num_workers: 4
        pin_memory: true
        seed: 42
        verbose: false
wandb:
    value:
        entity: mwfjord
        name: GNN Training
        project: structural_binding_affinity_predictions_using_gnn
        use_wandb: true
