_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 77
                - 106
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 77
                - 106
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.6
            "8":
                - 1
                - 5
            "12": 0.19.6
            "13": linux-x86_64
wandb:
    value:
        config:
            dataset:
                name: KLF1_K_d
                split_ratio:
                    test: 0.1
                    train: 0.8
                    validation: 0.1
            logging:
                log_interval: 10
                save_interval: 10
                save_model: true
            model:
                activation: relu
                hidden_units: 128
                layers: 3
                type: GNN
            training:
                batch_size: 32
                epochs: 100
                learning_rate: 0.001
                optimizer: adam
        entity: mwfjord
        name: GNN Training
        project: structural_binding_affinity_predictions_using_gnn
