_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.6
            "8":
                - 1
                - 5
            "12": 0.19.6
            "13": linux-x86_64
