wandb:
  project: "structural_binding_affinity_predictions_using_gnn"
  entity: "mwfjord"
  name: "GNN Training"
  use_wandb: False

hyperparameters:
    batch_size: [32, 128, 64]
    learning_rate: [0.1, 0.05, 0.01, 0.001]
    weight_decay: [0.0001, 0.00001, 0.001]
    sgd_momentum: [0.9, 0.8, 0.5]
    scheduler_gamma: [0.995, 0.9, 0.8, 0.5, 1]
    model_layers: [3]
    model_embedding_size: [8, 16, 32, 64, 128]
    model_top_k_ratio: [0.2, 0.5, 0.8, 0.9]
    model_top_k_every_n: [1]
    model_dense_neurons: [16, 128, 64, 256, 32]


dataset:
  name: "KLF1_K_d"
  path: "../data/"
  regenerate: False
  edge_inclusion_radius: 10 #Ångström
  max_Kd: 10.800759
  split_ratio: 
    train: 0.8
    validation: 0.1
    test: 0.1

logging:
  log_interval: 10
  save_model: true
  save_interval: 10

utility:
  device: "cuda"
  num_workers: 4
  pin_memory: True
  verbose: False
  debug: False
  seed: 42

tuner:
  optimizer: "bayesian"
  num_iterations: 10
  initial_random: 1


best_params:
  batch_size: 128
  learning_rate: 0.01
  model_dense_neurons: 32
  model_embedding_size: 128
  model_layers: 3
  model_top_k_every_n: 1
  model_top_k_ratio: 0.5
  scheduler_gamma: 1
  sgd_momentum: 0.5
  weight_decay: 0.001
